/**
 * ChatBootAI
 * This is ChatBootAI specification described as OpenAPI 3.0.  ChatBoot AI allows you to interact with several user interface and back-ends following the same OpenAPI contract.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Represents the message that is contained in the chat response returned by the model.
*/
export class ChatResponseMessage {
    /**
    * The contents of the message.
    */
    'content': string | null;
    'role': ChatResponseMessage.RoleEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "ChatResponseMessage.RoleEnum"
        }    ];

    static getAttributeTypeMap() {
        return ChatResponseMessage.attributeTypeMap;
    }
}

export namespace ChatResponseMessage {
    export enum RoleEnum {
        System = <any> 'system',
        User = <any> 'user',
        Assistant = <any> 'assistant',
        Function = <any> 'function'
    }
}
