/**
 * ChatBootAI
 * This is ChatBootAI specification described as OpenAPI 3.0.  ChatBoot AI allows you to interact with several user interface and back-ends following the same OpenAPI contract.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ChatRequestMessage {
    /**
    * The contents of the system message.
    */
    'content': string;
    /**
    * The role of the messages author.
    */
    'role': ChatRequestMessage.RoleEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "ChatRequestMessage.RoleEnum"
        }    ];

    static getAttributeTypeMap() {
        return ChatRequestMessage.attributeTypeMap;
    }
}

export namespace ChatRequestMessage {
    export enum RoleEnum {
        System = <any> 'system',
        User = <any> 'user',
        Assistant = <any> 'assistant',
        Function = <any> 'function'
    }
}
