// tslint:disable
/**
 * ChatBootAI
 * This is ChatBootAI specification described as OpenAPI 3.0.  ChatBoot AI allows you to interact with several user interface and back-ends following the same OpenAPI contract.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Error sent by ChatBoot.
 * @export
 * @interface ChatError
 */
export interface ChatError {
    /**
     * @type {number}
     * @memberof ChatError
     */
    statusCode?: number;
    /**
     * @type {string}
     * @memberof ChatError
     */
    code?: string;
    /**
     * @type {string}
     * @memberof ChatError
     */
    error?: string;
    /**
     * @type {string}
     * @memberof ChatError
     */
    message?: string;
}
