// tslint:disable
/**
 * ChatBootAI
 * This is ChatBootAI specification described as OpenAPI 3.0.  ChatBoot AI allows you to interact with several user interface and back-ends following the same OpenAPI contract.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ChatRequestMessage,
} from './';

/**
 * Represents the chat request sent to the model.
 * @export
 * @interface ChatRequest
 */
export interface ChatRequest {
    /**
     * A list of messages comprising the conversation so far.
     * @type {Array<ChatRequestMessage>}
     * @memberof ChatRequest
     */
    messages: Array<ChatRequestMessage>;
    /**
     * ID of the model to use.
     * @type {string}
     * @memberof ChatRequest
     */
    model?: string;
    /**
     * If set, partial message deltas will be sent, like in ChatGPT. Tokens will be sent as data-only server-sent events as they become available, with the stream terminated by a data DONE
     * @type {boolean}
     * @memberof ChatRequest
     */
    stream?: boolean;
    /**
     * What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.  We generally recommend altering this or top_p but not both.
     * @type {number}
     * @memberof ChatRequest
     */
    temperature?: number;
    /**
     * An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.  We generally recommend altering this or temperature but not both.
     * @type {number}
     * @memberof ChatRequest
     */
    top_p?: number;
    /**
     * A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.
     * @type {string}
     * @memberof ChatRequest
     */
    user?: string;
}
