// tslint:disable
/**
 * ChatBootAI
 * This is ChatBootAI specification described as OpenAPI 3.0.  ChatBoot AI allows you to interact with several user interface and back-ends following the same OpenAPI contract.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ChatRequestMessage
 */
export interface ChatRequestMessage {
    /**
     * The contents of the system message.
     * @type {string}
     * @memberof ChatRequestMessage
     */
    content: string;
    /**
     * The role of the messages author.
     * @type {string}
     * @memberof ChatRequestMessage
     */
    role: ChatRequestMessageRoleEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ChatRequestMessageRoleEnum {
    System = 'system',
    User = 'user',
    Assistant = 'assistant',
    Function = 'function'
}

