// tslint:disable
/**
 * ChatBootAI
 * This is ChatBootAI specification described as OpenAPI 3.0.  ChatBoot AI allows you to interact with several user interface and back-ends following the same OpenAPI contract.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ChatResponseChoice,
} from './';

/**
 * Represents the chat response returned by the model, based on the provided chat request.
 * @export
 * @interface ChatResponse
 */
export interface ChatResponse {
    /**
     * A unique identifier for the completion.
     * @type {string}
     * @memberof ChatResponse
     */
    id?: string;
    /**
     * A list of chat completion choices. Can be more than one.
     * @type {Array<ChatResponseChoice>}
     * @memberof ChatResponse
     */
    choices: Array<ChatResponseChoice>;
    /**
     * The object type, which is always \"chat\"
     * @type {string}
     * @memberof ChatResponse
     */
    object: ChatResponseObjectEnum;
    /**
     * The Unix timestamp (in seconds) of when the completion was created.
     * @type {number}
     * @memberof ChatResponse
     */
    created?: number;
    /**
     * The model used for the chat completion.
     * @type {string}
     * @memberof ChatResponse
     */
    model?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum ChatResponseObjectEnum {
    Chat = 'chat'
}

