// tslint:disable
/**
 * ChatBootAI
 * This is ChatBootAI specification described as OpenAPI 3.0.  ChatBoot AI allows you to interact with several user interface and back-ends following the same OpenAPI contract.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents the message that is contained in the chat response returned by the model.
 * @export
 * @interface ChatResponseMessage
 */
export interface ChatResponseMessage {
    /**
     * The contents of the message.
     * @type {string}
     * @memberof ChatResponseMessage
     */
    content: string | null;
    /**
     * @type {string}
     * @memberof ChatResponseMessage
     */
    role: ChatResponseMessageRoleEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ChatResponseMessageRoleEnum {
    System = 'system',
    User = 'user',
    Assistant = 'assistant',
    Function = 'function'
}

