/**
 * ChatBootAI
 * This is ChatBootAI specification described as OpenAPI 3.0.  ChatBoot AI allows you to interact with several user interface and back-ends following the same OpenAPI contract.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ChatError from '../ai.chatboot.model/ChatError';
import ChatRequest from '../ai.chatboot.model/ChatRequest';
import ChatResponse from '../ai.chatboot.model/ChatResponse';

/**
* Chat service.
* @module ai.chatboot.api/ChatAPI
* @version 0.0.1
*/
export default class ChatAPI {

    /**
    * Constructs a new ChatAPI. 
    * @alias module:ai.chatboot.api/ChatAPI
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the chat operation.
     * @callback module:ai.chatboot.api/ChatAPI~chatCallback
     * @param {String} error Error message, if any.
     * @param {module:ai.chatboot.model/ChatResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Engage a conversation with ChatBootAI
     * Post a prompt to ChatBootAI and receive a response
     * @param {Object} opts Optional parameters
     * @param {module:ai.chatboot.model/ChatRequest} [chatRequest] 
     * @param {module:ai.chatboot.api/ChatAPI~chatCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:ai.chatboot.model/ChatResponse}
     */
    chat(opts, callback) {
      opts = opts || {};
      let postBody = opts['chatRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ChatResponse;
      return this.apiClient.callApi(
        '/chat', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
