/**
 * ChatBootAI
 * This is ChatBootAI specification described as OpenAPI 3.0.  ChatBoot AI allows you to interact with several user interface and back-ends following the same OpenAPI contract.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChatRequestMessage { 
    /**
     * The contents of the system message.
     */
    content: string;
    /**
     * The role of the messages author.
     */
    role: ChatRequestMessage.RoleEnum;
}
export namespace ChatRequestMessage {
    export type RoleEnum = 'system' | 'user' | 'assistant' | 'function';
    export const RoleEnum = {
        System: 'system' as RoleEnum,
        User: 'user' as RoleEnum,
        Assistant: 'assistant' as RoleEnum,
        Function: 'function' as RoleEnum
    };
}


