// tslint:disable
/**
 * ChatBootAI
 * This is ChatBootAI specification described as OpenAPI 3.0.  ChatBoot AI allows you to interact with several user interface and back-ends following the same OpenAPI contract.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    ai.chatboot.model.ChatError,
    ai.chatboot.model.ChatRequest,
    ai.chatboot.model.ChatResponse,
} from '../models';

export interface ChatRequest {
    chatRequest?: ChatRequest;
}

/**
 * no description
 */
export class ChatAPI extends BaseAPI {

    /**
     * Post a prompt to ChatBootAI and receive a response
     * Engage a conversation with ChatBootAI
     */
    chat({ chatRequest }: ChatRequest): Observable<ChatResponse>
    chat({ chatRequest }: ChatRequest, opts?: OperationOpts): Observable<AjaxResponse<ChatResponse>>
    chat({ chatRequest }: ChatRequest, opts?: OperationOpts): Observable<ChatResponse | AjaxResponse<ChatResponse>> {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ChatResponse>({
            url: '/chat',
            method: 'POST',
            headers,
            body: chatRequest,
        }, opts?.responseOpts);
    };

}
